AUTO_RESUME: false
DATA_DIR: '/home/data/ywm_data/train_data/new_data_added/val_set/'  # 测试集数据路径
GPUS: (0,1,2,3,)
OUTPUT_DIR: './output'
LOG_DIR: './log'
WORKERS: 4
PRINT_FREQ: 50
PIN_MEMORY: true
# loss weight
LOSS:
  ALPHA: 5.0
# audio to sepc params
SPEC:
  HOPSIZE: 512
  SR: 44100
  SPEC_STYLE: 'cqt'
# cudnn params
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATASET:
  ROOT: '/home/data/ywm_data/train_data/shuffle_data/sep_dataset/'
#  ROOT: '/home/data/ywm_data/temp_data'
  DIR: ''
  VALID_SET: 'valid'
  TRAIN_SET: 'train'
  NEG_POS_RATE: 0.0
MODEL:
  INIT_WEIGHT: true
  NAME: bilstm
  INPUT_SIZE:
    - 9 # 时间帧长
    - 267 # 频点数
  OUTPUT_SIZE:
    - 1 #  时间帧长
    - 1 # 预测概率
  PRETRAINED: 'bi_lstm_87×267.pth'
  CBAM_ONSETNET:
    pad_length: 4
    spec_style: 'cqt'
    config: ''
  BI_LSTM:
    lstm_input_dim: 256
    lstm_hidden_dim: 512
    lstm_num_layers: 2
    lstm_output_dim: 128
    pre_trained_onsetnet: './Models/onset.pth'
TRAIN:
  THRESHOLD: 0.5
  BATCH_SIZE_PER_GPU: 64
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 60
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 30
  - 50
  WD: 0.00005
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE_PER_GPU: 32
  THRESHOLD: 0.5